import { Ranking } from "@/types/types";
import { BgWhite } from "../BgWhite";
import { columns } from "./tableRanking/columns";
import { TableRanking } from "./tableRanking/data";

export const TabGraham = () => {
  const tickersGraham: Ranking[] = [
    {
      id: "1",
      rank: 1,
      ticker: "AAPL",
      currentPrice: 150.5,
      fairValue: 180.0,
      dividendYield: 1.5,
      pvp: 15.0,
      safetyMargin: 16.4,
    },
    {
      id: "2",
      rank: 2,
      ticker: "MSFT",
      currentPrice: 250.0,
      fairValue: 290.0,
      dividendYield: 1.2,
      pvp: 14.0,
      safetyMargin: 16.0,
    },
    {
      id: "3",
      rank: 3,
      ticker: "GOOGL",
      currentPrice: 2800.0,
      fairValue: 3200.0,
      dividendYield: 1.1,
      pvp: 12.5,
      safetyMargin: 12.5,
    },
    {
      id: "4",
      rank: 4,
      ticker: "AMZN",
      currentPrice: 3500.0,
      fairValue: 4000.0,
      dividendYield: 0.9,
      pvp: 10.0,
      safetyMargin: 14.3,
    },
    {
      id: "5",
      rank: 5,
      ticker: "TSLA",
      currentPrice: 700.0,
      fairValue: 800.0,
      dividendYield: 1.3,
      pvp: 14.3,
      safetyMargin: 16.7,
    },
    {
      id: "6",
      rank: 6,
      ticker: "NFLX",
      currentPrice: 500.0,
      fairValue: 600.0,
      dividendYield: 1.4,
      pvp: 16.7,
      safetyMargin: 10.0,
    },
    {
      id: "7",
      rank: 7,
      ticker: "FB",
      currentPrice: 350.0,
      fairValue: 420.0,
      dividendYield: 1.6,
      pvp: 16.7,
      safetyMargin: 12.5,
    },
    {
      id: "8",
      rank: 8,
      ticker: "NVDA",
      currentPrice: 200.0,
      fairValue: 240.0,
      dividendYield: 1.2,
      pvp: 20.0,
      safetyMargin: 15.0,
    },
    {
      id: "9",
      rank: 9,
      ticker: "INTC",
      currentPrice: 60.0,
      fairValue: 72.0,
      dividendYield: 1.0,
      pvp: 16.7,
      safetyMargin: 14.3,
    },
    {
      id: "10",
      rank: 10,
      ticker: "AMD",
      currentPrice: 90.0,
      fairValue: 108.0,
      dividendYield: 1.4,
      pvp: 16.7,
      safetyMargin: 20.0,
    },
    {
      id: "11",
      rank: 11,
      ticker: "BABA",
      currentPrice: 220.0,
      fairValue: 264.0,
      dividendYield: 1.5,
      pvp: 20.0,
      safetyMargin: 16.0,
    },
    {
      id: "12",
      rank: 12,
      ticker: "V",
      currentPrice: 230.0,
      fairValue: 276.0,
      dividendYield: 1.6,
      pvp: 20.0,
      safetyMargin: 14.3,
    },
    {
      id: "13",
      rank: 13,
      ticker: "MA",
      currentPrice: 350.0,
      fairValue: 420.0,
      dividendYield: 1.7,
      pvp: 16.7,
      safetyMargin: 12.5,
    },
    {
      id: "14",
      rank: 14,
      ticker: "JPM",
      currentPrice: 160.0,
      fairValue: 192.0,
      dividendYield: 1.5,
      pvp: 20.0,
      safetyMargin: 15.0,
    },
    {
      id: "15",
      rank: 15,
      ticker: "WMT",
      currentPrice: 140.0,
      fairValue: 168.0,
      dividendYield: 1.3,
      pvp: 20.0,
      safetyMargin: 16.7,
    },
    {
      id: "16",
      rank: 16,
      ticker: "DIS",
      currentPrice: 170.0,
      fairValue: 204.0,
      dividendYield: 1.4,
      pvp: 18.0,
      safetyMargin: 20.0,
    },
    {
      id: "17",
      rank: 17,
      ticker: "KO",
      currentPrice: 60.0,
      fairValue: 72.0,
      dividendYield: 3.0,
      pvp: 18.0,
      safetyMargin: 16.7,
    },
    {
      id: "18",
      rank: 18,
      ticker: "PEP",
      currentPrice: 140.0,
      fairValue: 168.0,
      dividendYield: 2.8,
      pvp: 20.0,
      safetyMargin: 15.0,
    },
    {
      id: "19",
      rank: 19,
      ticker: "MCD",
      currentPrice: 220.0,
      fairValue: 264.0,
      dividendYield: 2.5,
      pvp: 18.0,
      safetyMargin: 14.3,
    },
    {
      id: "20",
      rank: 20,
      ticker: "CSCO",
      currentPrice: 50.0,
      fairValue: 60.0,
      dividendYield: 3.5,
      pvp: 15.0,
      safetyMargin: 20.0,
    },
  ];

  return (
    <BgWhite fullHeight>
      <TableRanking columns={columns} data={tickersGraham} />
    </BgWhite>
  );
};
